- name: Creates a sysctl configuration file to disable IPv6
  copy:
    content: |
      # DISABLE IPv6 system-wide
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1
    dest: /etc/sysctl.d/disable-ipv6.conf
  notify:
    - Reload the sysctl kernel parameters configuration from the filesystem
