---
- name: Reload the sysctl configuration
  # We have to use the shell module here because (to date) the
  # ansible.posix.sysctl module does not allow to force a reload
  shell:
    cmd: sysctl --system
